export const packages = [
  {
    title: "Paket Ekonomis",
    price: "Rp 25.000",
    min: "Min. 20 porsi",
    features: [
      "Nasi putih",
      "1 lauk pilihan",
      "1 sayur pilihan",
      "Sambal dan kerupuk",
      "Air mineral",
      "Kemasan box",
    ],
    buttonColor: "bg-[#D2A974]",
    textColor: "text-[#C07A5B]",
    border: "",
    popular: false,
  },
  {
    title: "Paket Spesial",
    price: "Rp 40.000",
    min: "Min. 30 porsi",
    features: [
      "Nasi putih / nasi kuning",
      "2 lauk pilihan",
      "2 sayur pilihan",
      "Sambal, lalapan, kerupuk",
      "Es teh manis / air mineral",
      "Kemasan box premium",
      "Free standing banner",
    ],
    buttonColor: "bg-leafGreen",
    textColor: "text-leafGreen",
    border: "border-4 border-leafGreen",
    popular: true,
  },
  {
    title: "Paket Premium",
    price: "Rp 60.000",
    min: "Min. 50 porsi",
    features: [
      "Nasi putih / nasi kuning / nasi goreng",
      "3 lauk pilihan (termasuk seafood)",
      "2 sayur pilihan",
      "Sambal, lalapan, kerupuk, acar",
      "Es teh manis + air mineral",
      "Kemasan box premium + dekorasi",
      "Free standing banner + backdrop",
      "Free dessert / buah",
    ],
    buttonColor: "bg-[#E4573D]",
    textColor: "text-[#E4573D]",
    border: "",
    popular: false,
  },
];
